server:
  port: 8080
#  servlet:
#    context-path: /aix

#开发环境
env:
  host: ds.com


#业务配置
aix:
  init-flag: true
  custom-file:
    root: D://haizhi//config//data-for-1.7.5//data//dictionary//custom
    mongo: ${aix.custom-file.root}//mongo.txt

spring:
  application:
    name: aix
  #Redis 配置
  redis:
    # Redis服务器地址
    host: ${env.host}
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 链接超时时间 单位 ms（毫秒）
    timeout: 3000
    # Redis 线程池设置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 3000
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

  # json 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

