server:
  port: 8080
#  servlet:
#    context-path: /aix

#开发环境
env:
  host: ds.com

#业务配置
aix:
  init-flag: true
  custom-file:
    root: D://haizhi//config//data-for-1.7.5//data//dictionary//custom
    question: ${aix.custom-file.root}//question.txt
    company: ${aix.custom-file.root}//company.txt

spring:
  application:
    name: aix


